#!/usr/bin/env bash

prefixes=(
    'adventurous'
    'affable'
    'ambitious'
    'amiable '
    'amusing'
    'brave'
    'bright'
    'charming'
    'compassionate'
    'convivial'
    'courageous'
    'creative'
    'diligent'
    'easygoing'
    'emotional'
    'energetic'
    'enthusiastic'
    'exuberant'
    'fearless'
    'friendly'
    'funny'
    'generous'
    'gentle'
    'good'
    'helpful'
    'honest'
    'humorous'
    'imaginative'
    'independent'
    'intelligent'
    'intuitive'
    'inventive'
    'kind'
    'loving'
    'loyal'
    'modest'
    'neat'
    'nice'
    'optimistic'
    'passionate'
    'patient'
    'persistent'
    'polite'
    'practical'
    'rational'
    'reliable'
    'reserved'
    'resourceful'
    'romantic'
    'sensible'
    'sensitive'
    'sincere'
    'sympathetic'
    'thoughtful'
    'tough'
    'understanding'
    'versatile'
    'warmhearted'
)

cat >./src/lib/names.ts <<EOF
// This file is generated by scripts/gen-icons-ts.sh

export const icons = [
$(find ./public/icons -type f -name '*.svg' -exec basename {} \; | sed 's/.svg//g' | sort |
    xargs -I {} echo "    '{}',")
];

export const prefixes = [
$(printf "%s\n" "${prefixes[@]}" | xargs -I {} echo "    '{}',")
];
EOF
