#!/usr/bin/env bash

set -Eeo pipefail

cd "$(dirname "$0")/.."
pwd

prefixes=("adaptable" "affectionate" "agile" "alert" "amazing" "athletic" "beautiful" "brave" "bright" "calm" "caring" "cheerful" "clever" "colorful" "compassionate" "courageous" "curious" "dashing" "dedicated" "dignified" "disciplined" "elegant" "energetic" "enthusiastic" "exotic" "fearless" "friendly" "gentle" "graceful" "hardworking" "healthy" "intelligent" "joyful" "kind" "loyal" "majestic" "noble" "observant" "passionate" "patient" "playful" "powerful" "precise" "proud" "quick" "quiet" "resilient" "respectful" "robust" "sensitive" "smart" "sociable" "strong" "stunning" "subtle" "tenacious" "terrific" "tough" "trustworthy" "unstoppable" "vibrant" "vigorous" "warm" "wild" "wise" "witty" "wonderful" "zealous" "zippy" "adorable" "bold" "charming" "determined" "endearing" "faithful" "gallant" "happy" "impressive" "jovial" "keen" "lively" "merry" "nimble" "optimistic" "peppy" "quirky" "radiant" "spirited" "tranquil" "upbeat" "valiant" "wholesome" "xenial" "youthful" "zesty" "adventurous" "benevolent" "confident" "devoted" "exciting" "fantastic" "generous" "heroic" "inspiring" "jubilant" "light-hearted" "magnificent" "nurturing" "outgoing" "persevering" "reliable" "sympathetic" "thrilling" "undaunted" "vivacious" "witty" "xtraordinary" "yearning" "zealful")

cat >./src/lib/names.ts <<EOF
// This file is generated by scripts/gen-icons-ts.sh

export const icons = [
$(find ./public/icons -type f -name '*.svg' -exec basename {} \; | sed 's/.svg//g' | sort | grep -v 'default' | xargs -I {} echo "  '{}',")
];

export const prefixes = [
$(printf "%s\n" "${prefixes[@]}" | xargs -I {} echo "  '{}',")
];
EOF
